name: JUnit Tests

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "17"

      - name: Download JUnit Platform Console
        run: wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.0/junit-platform-console-standalone-1.8.0.jar

      - name: Build and Run JUnit Tests
        run: |
          javac -cp junit-platform-console-standalone-1.8.0.jar:src:tests:lib/* YourTestFile.java
          java -jar junit-platform-console-standalone-1.8.0.jar --class-path junit-platform-console-standalone-1.8.0.jar:src:tests:lib/* --scan-classpath

